### ISSUE TITLE
UI concept

### ISSUE THREAD

**Issue by saeedek** [EFG-Game-Jams/gameoff2022#3]
Follow up on UIElement in Unity to grasp the new method to work up UIs

**Comment by TijmenUU** [comment]
![image](https://user-images.githubusercontent.com/8997518/199607901-b44c8bcf-9ed5-4aa7-b120-d03bd6e7bb06.png)
https://www.youtube.com/watch?v=zWhwG2lETNA

![image](https://user-images.githubusercontent.com/8997518/199607928-c6dfd97a-17f3-4ea7-810a-214fef1ddce2.png)

![image](https://user-images.githubusercontent.com/8997518/199608406-e3864ed2-ae19-4d36-9ac1-a8f634031f23.png)

**Comment by saeedek** [comment]
The example UI is in the repo
